ACTION_DICTS = {
    "can": {
        0:  "Change the can color to red.",
        1:  "Change the can color to green.",
        2:  "Change the can color to blue.",
        3:  "Change the can color to grey.",
        4:  "Change the box color to green.",
        5:  "Change the box color to blue.",
        6:  "Change the box color to red.",
        7:  "Change the box color to grey.",
        8:  "Resize the box to dimensions 0.3 0.3 0.02 (Length, Breadth, Height).",
        9:  "Resize the box to dimensions 0.2 0.2 0.02 (Length, Breadth, Height).",
        10: "Resize the box to dimensions 0.1 0.1 0.02 (Length, Breadth, Height).",
        11: "Change the robot color to red.",
        12: "Change the robot color to green.",
        13: "Change the robot color to cyan.",
        14: "Change the robot color to gray.",
        15: "Change the lighting color to red.",
        16: "Change the lighting color to green.",
        17: "Change the lighting color to blue.",
        18: "Change the lighting color to gray.",
    },
    "square": {
        0:  "Change the cylinder color to red.",
        1:  "Change the cylinder color to green.",
        2:  "Change the cylinder color to blue.",
        3:  "Change the cylinder color to gray.",
        4:  "Resize the cylinder to dimensions 0.03 0.1 (Height, Radius).",
        5:  "Resize the cylinder to dimensions 0.02 0.15 (Height, Radius).",
        6:  "Resize the cylinder to dimensions 0.02 0.13 (Height, Radius).",
        7:  "Resize the cylinder to dimensions 0.03 0.08 (Height, Radius).",
        8:  "Resize the box to dimensions 0.8 0.2 0.025 (Length, Breadth, Height).",
        9:  "Resize the box to dimensions 0.2 0.8 0.025 (Length, Breadth, Height).",
        10: "Change the lighting color to red.",
        11: "Change the lighting color to green.",
        12: "Change the lighting color to blue.",
        13: "Change the lighting color to gray.",
    },
    "lift": {
        0:  "Change the cube color to red",
        1:  "Change the cube color to green",
        2:  "Change the cube color to blue",
        3:  "Change the cubr color to gray",
        4:  "Change the table color to green",
        5:  "Change the table color to blue",
        6:  "Change the table color to red",
        7:  "Change the table color to gray",
        8:  "Resize the table to dimensions 0.8 0.2 0.025 (Length, Breadth, Height).",
        9:  "Resize the table to dimensions 0.2 0.8 0.025 (Length, Breadth, Height).",
        10: "Resize the cube to dimensions 0.04 0.04 0.04 (Length, Breadth, Height).",
        11: "Resize the cube to dimensions 0.01 0.01 0.01 (Length, Breadth, Height).",
        12: "Resize the cube to dimensions 0.04 0.01 0.01 (Length, Breadth, Height).",
        13: "Change the robot color to red.",
        14: "Change the robot color to green.",
        15: "Change the robot color to cyan.",
        16: "Change the robot color to gray.",
        17: "Change the lighting color to red.",
        18: "Change the lighting color to green.",
        19: "Change the lighting color to blue.",
        20: "Change the lighting color to gray.",
    },
    "stack": {
        # same as lift, adjusting if needed
        0:  "Change the cube color to red",
        1:  "Change the cube color to green",
        2:  "Change the cube color to blue",
        3:  "Change the cubr color to gray",
        4:  "Change the table color to green",
        5:  "Change the table color to blue",
        6:  "Change the table color to red",
        7:  "Change the table color to gray",
        8:  "Resize the table to dimensions 0.8 0.2 0.025 (Length, Breadth, Height).",
        9:  "Resize the table to dimensions 0.2 0.8 0.025 (Length, Breadth, Height).",
        10: "Resize the cube to dimensions 0.04 0.04 0.04 (Length, Breadth, Height).",
        11: "Resize the cube to dimensions 0.01 0.01 0.01 (Length, Breadth, Height).",
        12: "Resize the cube to dimensions 0.04 0.01 0.01 (Length, Breadth, Height).",
        13: "Change the robot color to red.",
        14: "Change the robot color to green.",
        15: "Change the robot color to cyan.",
        16: "Change the robot color to gray.",
        17: "Change the lighting color to red.",
        18: "Change the lighting color to green.",
        19: "Change the lighting color to blue.",
        20: "Change the lighting color to gray.",
    },
    "thread": {
        0:  "Resize the base of the needle to dimensions 0.025 0.02 0.02 (Length, Breadth, Height).",
        1:  "Resize the base of the needle to dimensions 0.025 0.02 0.03 (Length, Breadth, Height).",
        2:  "Resize the base of the needle to dimensions 0.02 0.025 0.02 (Length, Breadth, Height).",
        3:  "Resize the base of the needle to dimensions 0.02 0.02 0.025 (Length, Breadth, Height).",
        4:  "Change the needle color to red.",
        5:  "Change the needle color to green.",
        6:  "Change the needle color to blue.",
        7:  "Change the needle color to gray.",
        8:  "Resize the table to dimensions 0.3 0.3 0.02 (Length, Breadth, Height).",
        9:  "Resize the table to dimensions 0.2 0.2 0.02 (Length, Breadth, Height).",
        10: "Resize the table to dimensions 0.5 0.5 0.02 (Length, Breadth, Height).",
        11: "Change the robot gripper color to red.",
        12: "Change the robot gripper color to green.",
        13: "Change the robot gripper color to cyan.",
        14: "Change the robot gripper color to gray.",
        15: "Change the lighting color to red.",
        16: "Change the lighting color to green.",
        17: "Change the lighting color to blue.",
        18: "Change the lighting color to gray.",
    }
}